# -*- coding: utf-8 -*-
"""Lab1_ComputationalChemistry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9plxELrUDriAqFDcaXYBjFuMy5NLY74

**Nandini Bajaj 18CY20020**

Lab Assignment 1
"""

def ke_one_particle(vx, vy, vz, m):
  return ((vx*vx) + (vy*vy) + (vz*vz)) * m /2

def ke_of_same_mass(n_1, v_x, v_y, v_z, m_1):          
  ans = 0
  for i in range(n_1):
    ans += ke_one_particle(v_x[i], v_y[i], v_z[i], m_1)
  return ans

n_1 = int(input("Enter the number of particles:  "))          
m_1 = float(input("Enter the mass of the particle:  "))
v_ix = []
v_iy = []
v_iz = []
for i in range(n_1):
    print("Enter x component of velocity of particle", i+1, ": ")
    v_ix.append(float(input()))
    print("Enter y component of velocity of particle", i+1, ": ")
    v_iy.append(float(input()))
    print("Enter z component of velocity of particle", i+1, ": ")
    v_iz.append(float(input()))

print("KE of the system containing 10 particles: ", ke_of_same_mass(n_1, v_ix, v_iy, v_iz, m_1))

