# -*- coding: utf-8 -*-
"""ComputationalChemistry_Lab7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGdXrmhYtSk8dP-ZGo6QiPUIapD9Rcoh

**Nandini Bajaj 18CY20020**

Lab Assignment 7
"""

import pandas as pd
import numpy as np
import math
import random
import matplotlib.pyplot as plt

def cubic(l, n):
  count=0
  for i in range(7):
    for j in range(7):
      for k in range(7):
        config.append([l*k, l*j, l*i])
        count+=1
        if count == n:
          break

def fcc(l, n):
  count=0
  for i in range(16):
    for j in range(4):
      for k in range(4):
        if i%2 == 0:
          if j%2==0:
            config_fcc.append([k*l, j*l, (i%4)*l])
          else:
            config_fcc.append([l/2+k*l, l/2+j*l, l/2+(i%4)*l])
        else:
          if j%2!=0:
            config_fcc.append([k*l, j*l, (i%4)*l])
          else:
            config_fcc.append([l/2+k*l, l/2+j*l, l/2+(i%4)*l])

config_fcc=[]
config=[]
n=256
cubic(3.1034, n)
print("Coordinates for cubic configuration:")
for i in range(n):
  print(str(config[i][0])+"   "+str(config[i][1])+"   "+str(config[i][2]))

fcc(4.9264, n)
print("Coordinates for FCC configuration:")
for i in range(n):
  print(str(config_fcc[i][0])+"   "+str(config_fcc[i][1])+"   "+str(config_fcc[i][2]))

config

config_fcc

import csv
with open("cubic_config.csv","w+") as my_csv:
    csvWriter = csv.writer(my_csv,delimiter=',')
    csvWriter.writerows(config)

import csv
with open("fcc_config.csv","w+") as my_csv:
    csvWriter = csv.writer(my_csv,delimiter=',')
    csvWriter.writerows(config_fcc)

